module.exports = {
    PORT: process.env.PORT,
    DATABASE: process.env.DATABASE,
    JWT_SECRET: process.env.JWT_SECRET,
    ACCESS_TOKEN_VALIDITY: process.env.ACCESS_TOKEN_VALIDITY,
    REFRESH_SECRET: process.env.REFRESH_SECRET,
    REFRESH_TOKEN_VALIDITY: process.env.REFRESH_TOKEN_VALIDITY,
    SMS_API_KEY: process.env.SMS_API_KEY,
    FAST2SMS: process.env.FAST2SMS,
    CLOUD_NAME: process.env.CLOUD_NAME,
    IMAGE_API_KEY: process.env.IMAGE_API_KEY,
    IMAGE_API_SECRET: process.env.IMAGE_API_SECRET,
    MAX_RETRIES: process.env.MAX_RETRIES,
    RETRY_DELAY_MS: process.env.RETRY_DELAY_MS,
    EMAIL_USER: process.env.EMAIL_USER,
    EMAIL_PASS: process.env.EMAIL_PASS,
    // Firebase config
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_PRIVATE_KEY_ID: process.env.FIREBASE_PRIVATE_KEY_ID,
    FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
    FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
    FIREBASE_CLIENT_ID: process.env.FIREBASE_CLIENT_ID,
    // RAZORPAY
    RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
    // sms
    SMS_USER: process.env.SMS_USER,
    SMS_PASSWORD: process.env.SMS_PASSWORD,
    SMS_SENDER: process.env.SMS_SENDER,
    SMS_CHANNEL: process.env.SMS_CHANNEL,
    SMS_ROUTE: process.env.SMS_ROUTE,
    SMS_OTP_TEMPLATE_ID: process.env.SMS_OTP_TEMPLATE_ID,
    SMS_PEID: process.env.SMS_PEID,
}